version: "2.2"

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: ./api/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    restart: unless-stopped
    build: ./api
    env_file: ./api/.env
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./api:/app
    stdin_open: true
    tty: true

volumes:
  db-data:
