version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    container_name: api
    depends_on:
      - db
    restart: unless-stopped
    build: ./api
    env_file: ./api/.env
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    stdin_open: true
    tty: true
  web:
    container_name: web
    depends_on:
      - db
      - api
    restart: unless-stopped
    build: ./web
    env_file: ./web/.env
    ports:
      - 3001:3000
    volumes:
      - ./web:/app
    stdin_open: true
    tty: true

volumes:
  db-data: