import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import TanstackProvider from "~/providers/TanstackProvider";
import { ThemeProvider } from "~/providers/ThemeProvider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <TanstackProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          themes={["light", "dark", "system"]}
          enableSystem
          disableTransitionOnChange
        >

          <body>{children}</body>
        </ThemeProvider>
      </TanstackProvider>
    </html>
  );
}
